### ISSUE TITLE
Gradle Tasks trace log Chinese garbled

### ISSUE THREAD

**Issue by mozhuanzuojing** [badsyntax/vscode-gradle#1001]
Extension Name: vscode-gradle
Extension Version: 3.7.1 and 3.8.0
OS Version:window10 21H1
VSCode version:1.61

**Describe the bug**
After the gradle project is initialized, check the Gradle Tasks log, there are garbled Chinese characters

**To Reproduce**
1. git pull https://gitee.com/mozhuanzuojing/java-bug01
2. Open it by VS Code
3. wait building
4. view Gradle Tasks log

**Expected behavior**
Chinese output correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/63572041/133374640-29b7269c-3993-419f-936b-81be04a3acf6.png)

**Output from "Gradle Tasks"**
```log
[info] [gradle-server] Server started, listening on 14999
[info] Gradle client connected to server
[info] Java Home: C:\Program Files\AdoptOpenJDK\jdk-16.0.1.9-hotspot
[info] JVM Args: -XX:MaxMetaspaceSize=512m,-XX:+UseShenandoahGC,-XX:MinHeapFreeRatio=20,-XX:MaxHeapFreeRatio=40,-XX:GCTimeRatio=4,-XX:AdaptiveSizePolicyWeight=90,-XX:+HeapDumpOnOutOfMemoryError,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-Xms2g,-Xmx4g,-Dfile.encoding=UTF-8,-Duser.country=CN,-Duser.language=zh,-Duser.variant
[info] Gradle User Home: D:\java\gradlehome
[info] Gradle Version: 7.2
[info] > Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava UP-TO-DATE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test UP-TO-DATE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :
11111112
[configuration ':annotationProcessor', configuration ':api', configuration ':apiElements', configuration ':archives', configuration ':checkstyle', configuration ':compileClasspath', configuration ':compileOnly', configuration ':compileOnlyApi', configuration ':default', configuration ':implementation', configuration ':pmd', configuration ':pmdAux', configuration ':runtimeClasspath', configuration ':runtimeElements', configuration ':runtimeOnly', configuration ':testAnnotationProcessor', configuration ':testCompileClasspath', configuration ':testCompileOnly', configuration ':testImplementation', configuration ':testRuntimeClasspath', configuration ':testRuntimeOnly']
[���ý׶�] - ���ý׶� 01.
[hook] - ���ý׶���ɺ�,build.gradle������.
[hook] - ������ɺ�

CONFIGURE SUCCESSFUL in 3s
9 actionable tasks: 9 up-to-date
[info] Found 157 tasks
```

**Does the bug still exist if you disable all other extensions?**
Yes

**Additional context**

**Comment by badsyntax** [comment]
@mozhuanzuojing Can you paste the output of Gradle when using the gradlew.bat wrapper from the cmd line?

`gradlew.bat :buildSrc:compileJava`

**Comment by mozhuanzuojing** [comment]
> @mozhuanzuojing Can you paste the output of Gradle when using the gradlew.bat wrapper from the cmd line?
> 
> `gradlew.bat :buildSrc:compileJava`

same problem

**Comment by badsyntax** [comment]
@mozhuanzuojing Can you add the following to `gradle.properties` (either in your home directory, or in the root of your project):

```
org.gradle.jvmargs='-Dfile.encoding=UTF-8'
```

Can you let us know if that fixes things?

**Comment by mozhuanzuojing** [comment]
> @mozhuanzuojing Can you add the following to `gradle.properties` (either in your home directory, or in the root of your project):
> 
> ```
> org.gradle.jvmargs='-Dfile.encoding=UTF-8'
> ```
> 
> Can you let us know if that fixes things?

Sorry, using utf8 parameters did not fix garbled characters.

> Only use the following method to output normally
```gradle
// build.gradle
 println new String("中文".getBytes(), "GB18030")

```

**Comment by badsyntax** [comment]
Thanks for letting me know. That fact that you see the garbled characters when using the gradle wrapper implies this is not a problem with this extension but rather with gradle encoding. It's not clear how to set the encoding correctly to fix this. I have also tried (powershell) `$env:GRADLE_OPTS = '-Dfile.encoding=UTF-8'` but still not seeing what we expect.

This is what I've been using to test:

```groovy
tasks.register("hello") {
    doLast {
        println "中文"
        println "File encoding: " + System.getProperty("file.encoding")
    }
}
```

And this is what I'm seeing (Windows/powershell):

```console
❯ .\gradlew.bat hello

> Task :hello
Σ╕¡µûç
File encoding: utf-8

BUILD SUCCESSFUL in 998ms
1 actionable task: 1 executed
```

**Comment by CsCherrYY** [comment]
I find a strange behavior about this issue. At the beginning I can reproduce this issue by simply open this sample project. With all the settings are default:
```
[info] [gradle-server] Server started, listening on 54980
[info] Gradle client connected to server
[info] Java Home: C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot
[info] JVM Args: --add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=windows-1252,-Duser.country=US,-Duser.language=en,-Duser.variant
[info] Gradle User Home: C:\Users\xxx\.gradle
[info] Gradle Version: 7.2
[info] > Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava UP-TO-DATE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test UP-TO-DATE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :
DeploymentPlugin-112233
[configuration ':annotationProcessor', configuration ':api', configuration ':apiElements', configuration ':archives', configuration ':checkstyle', configuration ':compileClasspath', configuration ':compileOnly', configuration ':compileOnlyApi', configuration ':default', configuration ':implementation', configuration ':instrumentedJars', configuration ':javadocElements', configuration ':pmd', configuration ':pmdAux', configuration ':runtimeClasspath', configuration ':runtimeElements', configuration ':runtimeOnly', configuration ':sourcesElements', configuration ':testAnnotationProcessor', configuration ':testCompileClasspath', configuration ':testCompileOnly', configuration ':testImplementation', configuration ':testRuntimeClasspath', configuration ':testRuntimeOnly']
[????] - ???? 01.
[hook] - ???????,build.gradle???.
[hook] - ?????

CONFIGURE SUCCESSFUL in 717ms
9 actionable tasks: 9 up-to-date
[info] Found 174 tasks
```

I notice that `-Dfile.encoding` is set to `windows-1252` by default. I go to the extension installation directory: `C:/Users/xxx/.vscode/extensions/vscjava.vscode-gradle-3.8.0/lib`, change line 36 to `set DEFAULT_JVM_OPTS= -Dfile.encoding=UTF-8` and reload the window. The Chinese logs show correctly.
```
[info] [gradle-server] Server started, listening on 51044
[info] Gradle client connected to server
[info] Java Home: C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot
[info] JVM Args: --add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.base/java.lang=ALL-UNNAMED,--add-opens,java.base/java.lang.invoke=ALL-UNNAMED,--add-opens,java.base/java.util=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.prefs/java.util.prefs=ALL-UNNAMED,--add-opens,java.base/java.nio.charset=ALL-UNNAMED,--add-opens,java.base/java.net=ALL-UNNAMED,--add-opens,java.base/java.util.concurrent.atomic=ALL-UNNAMED,-XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant
[info] Gradle User Home: C:\Users\xxx\.gradle
[info] Gradle Version: 7.2
[info] > Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava UP-TO-DATE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test UP-TO-DATE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :
DeploymentPlugin-112233
[configuration ':annotationProcessor', configuration ':api', configuration ':apiElements', configuration ':archives', configuration ':checkstyle', configuration ':compileClasspath', configuration ':compileOnly', configuration ':compileOnlyApi', configuration ':default', configuration ':implementation', configuration ':instrumentedJars', configuration ':javadocElements', configuration ':pmd', configuration ':pmdAux', configuration ':runtimeClasspath', configuration ':runtimeElements', configuration ':runtimeOnly', configuration ':sourcesElements', configuration ':testAnnotationProcessor', configuration ':testCompileClasspath', configuration ':testCompileOnly', configuration ':testImplementation', configuration ':testRuntimeClasspath', configuration ':testRuntimeOnly']
[配置阶段] - 配置阶段 01.
[hook] - 配置阶段完成后,build.gradle解析后.
[hook] - 构建完成后

CONFIGURE SUCCESSFUL in 882ms
9 actionable tasks: 9 up-to-date
[info] Found 174 tasks
```

But in @mozhuanzuojing 's log the `-Dfile.encoding` is set to `UTF-8` already, so I'm not sure the above test is helpful. @badsyntax do you think it's related to this issue?

**Comment by badsyntax** [comment]
@CsCherrYY I've been able to discover some new information. Firstly, when I was testing this, my terminal (cmd.exe or powershell) did not actually support utf8 by default so my initial tests were all wrong. I have now confirmed we can fix this in gradle by supplying the `GRADLE_OPTS` environment variable eg ` set GRADLE_OPTS=-Dfile.encoding=utf-8`

This does not work in the extension though because `GRADLE_OPTS` are not passed to the java process because we use https://docs.gradle.org/current/dsl/org.gradle.jvm.application.tasks.CreateStartScripts.html to generate the scripts to start the java process. See also: https://github.com/microsoft/vscode-gradle/blob/main/gradle-server/src/main/resources/startScriptTemplates/windowsStartScript.txt

To see the differences, look at:

- https://github.com/microsoft/vscode-gradle/blob/65ffe6c6145519848680b3899843ff115c831359/gradlew.bat#L88
- https://github.com/microsoft/vscode-gradle/blob/65ffe6c6145519848680b3899843ff115c831359/gradle-server/src/main/resources/startScriptTemplates/windowsStartScript.txt#L92

I assumed startscripts will give us essentially the same scripts as the gradle wrapper scripts but that's not the case.

A temporary workaround is to set `JAVA_OPTS` instead of `GRADLE_OPTS`. eg `set JAVA_OPTS=-Dfile.encoding=utf-8`, but I had to make this "global" by setting this in system in control panel. Then I restarted VS Code and then I could see the correct character encoding:

```console
[info] [gradle-server] Server started, listening on 53972
[info] Gradle client connected to server
[info] Java Home: C:\Program Files\AdoptOpenJDK\jdk-8.0.282.8-hotspot
[info] JVM Args: -Dfile.encoding=UTF-8,-Duser.country=GB,-Duser.language=en,-Duser.variant
[info] Gradle User Home: C:\Users\richard.willis\.gradle
[info] Gradle Version: 7.2
[info] > Task :buildSrc:compileJava UP-TO-DATE
> Task :buildSrc:compileGroovy UP-TO-DATE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources UP-TO-DATE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava UP-TO-DATE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test UP-TO-DATE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE

> Configure project :
DeploymentPlugin-112233
[configuration ':annotationProcessor', configuration ':api', configuration ':apiElements', configuration ':archives', configuration ':checkstyle', configuration ':compileClasspath', configuration ':compileOnly', configuration ':compileOnlyApi', configuration ':default', configuration ':implementation', configuration ':instrumentedJars', configuration ':javadocElements', configuration ':pmd', configuration ':pmdAux', configuration ':runtimeClasspath', configuration ':runtimeElements', configuration ':runtimeOnly', configuration ':sourcesElements', configuration ':testAnnotationProcessor', configuration ':testCompileClasspath', configuration ':testCompileOnly', configuration ':testImplementation', configuration ':testRuntimeClasspath', configuration ':testRuntimeOnly']
[配置阶段] - 配置阶段 01.
[hook] - 配置阶段完成后,build.gradle解析后.
[hook] - 构建完成后

CONFIGURE SUCCESSFUL in 8s
9 actionable tasks: 9 up-to-date
[info] Found 173 tasks
```

----

Regarding a fix for this extension and to support `GRADLE_OPTS` (the more standard way of setting gradle character encoding) I am not sure the correct approach. Maybe you can just adjust the startscript templates to forward GRADLE_OPTS? 

Sadly it looks like we can't set encoding in gradle.properties (because by the time gradle reads gradle.properties, it's process has already started) so we have to set it with an ENV var, which is rather inconvenient.

**Comment by badsyntax** [comment]
I am not sure if my analysis of the problem is entirely correct, but it seems like a good starting point to debug this.

**Comment by CsCherrYY** [comment]
@badsyntax Thank you! Agree that specifying encoding in `GRADLE_OPTS` is a better approach (than what I had try in `DEFAULT_JVM_OPTS`), but my concern is still if it is actually related to this issue (in the above log UTF-8 still has an encoding issue). 

@mozhuanzuojing Could you please help us to verify? You can follow the steps:
- Open your extension installation folder, it seems you're using windows, try to open `C:/Users/YOUR_NAME/.vscode/extensions/vscjava.vscode-gradle-3.8.0/lib`
- Open `gradle-server.bat` in a text editor (e.g. VSCode)
- Insert a new line under line 36, the content is `set GRADLE_SERVER_OPTS= -Dfile.encoding=UTF-8`, now the part of the script looks like
```
@rem Resolve any "." and ".." in APP_HOME to make it shorter.
for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi

@rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_SERVER_OPTS to pass JVM options to this script.
set DEFAULT_JVM_OPTS=
set GRADLE_SERVER_OPTS= -Dfile.encoding=UTF-8

@rem Find java.exe
if defined VSCODE_JAVA_HOME goto findJavaFromJavaHome
if defined JAVA_HOME goto findJavaFromJavaHome
```
- Save this file, and reload VSCode
- See if the encoding is correct

**Comment by badsyntax** [comment]
@CsCherrYY are you saying the logs i posted contain utf-8 encoding issue? the logs seems fine to me.

 i can't explain why, even though jvm args [show the file encoding](https://github.com/microsoft/vscode-gradle/blob/6f952cd5279435d14b659cb6dd8d2d56e2081360/gradle-server/src/main/java/com/github/badsyntax/gradle/handlers/GetBuildHandler.java#L201) is set to `UTF-8`, why we still have to set the encoding with `GRADLE_OPTS`. It doesn't make sense to me, but perhaps it's got something to do with how gradle forks processes?

**Comment by mozhuanzuojing** [comment]
@CsCherrYY @badsyntax 

> @badsyntax Thank you! Agree that specifying encoding in `GRADLE_OPTS` is a better approach (than what I had try in `DEFAULT_JVM_OPTS`), but my concern is still if it is actually related to this issue (in the above log UTF-8 still has an encoding issue).
> 
> @mozhuanzuojing Could you please help us to verify? You can follow the steps:
> 
> * Open your extension installation folder, it seems you're using windows, try to open `C:/Users/YOUR_NAME/.vscode/extensions/vscjava.vscode-gradle-3.8.0/lib`
> * Open `gradle-server.bat` in a text editor (e.g. VSCode)
> * Insert a new line under line 36, the content is `set GRADLE_SERVER_OPTS= -Dfile.encoding=UTF-8`, now the part of the script looks like
> 
> ```
> @rem Resolve any "." and ".." in APP_HOME to make it shorter.
> for %%i in ("%APP_HOME%") do set APP_HOME=%%~fi
> 
> @rem Add default JVM options here. You can also use JAVA_OPTS and GRADLE_SERVER_OPTS to pass JVM options to this script.
> set DEFAULT_JVM_OPTS=
> set GRADLE_SERVER_OPTS= -Dfile.encoding=UTF-8
> 
> @rem Find java.exe
> if defined VSCODE_JAVA_HOME goto findJavaFromJavaHome
> if defined JAVA_HOME goto findJavaFromJavaHome
> ```
> 
> * Save this file, and reload VSCode
> * See if the encoding is correct

> ## The test was successful just now, and the Chinese display is correct.


![image](https://user-images.githubusercontent.com/63572041/136638965-756f0d7b-19ac-469a-8fed-7b96b5f11c27.png)

**Comment by mozhuanzuojing** [comment]
@CsCherrYY @badsyntax 

> Under the following configuration. Print tasks in Chinese can also be output normally.
`set GRADLE_SERVER_OPTS= -Dfile.encoding=UTF-8`

```gradle
task chineseOutput(){
    println "********************************************"
    println "中文"
    println "********************************************"
}
```

![image](https://user-images.githubusercontent.com/63572041/136639133-5b833c70-9112-47c5-a2d5-d1eace21fa80.png)

**Comment by CsCherrYY** [comment]
> @CsCherrYY are you saying the logs i posted contain utf-8 encoding issue? the logs seems fine to me.

No. I'm just curious about @mozhuanzuojing 's first comment, where the encoding has been set to utf-8 already but the issue still exists. Since the test is successful, maybe we can do something in our template, which starts the server, to address this issue?

**Comment by CsCherrYY** [comment]
verified in #1048
