### ISSUE TITLE
Local Gradle install is not used when java.import.gradle.home is set

### ISSUE THREAD

**Issue by brendansailer** [badsyntax/vscode-gradle#1004]
Extension Name: vscode-gradle
Extension Version: 3.6.1
OS Version: Centos 7
VSCode version: 1.54.3

**Describe the bug**
Despite having java.import.gradle.home set to my local directory which has a Gradle 5.6.4 installed, it tries to download Gradle from the internet.

**To Reproduce**
Set java.import.gradle.wrapper.enabled to false, java.import.gradle.home to the proper directory, and java.import.gradle.version to the proper version.  Then reload your window and it'll still download Gradle.  If you leave off the version setting, you get an error so I believe that's required.

**Expected behavior**
Use my local Gradle install first rather than reaching out to the internet.

**Output from "Gradle Tasks"**
The first three lines are it connecting to the server and trying to download Gradle.

**Does the bug still exist if you disable all other extensions?**
Yes

Thanks for the help! I couldn't figure out how to get an account on Slack, so I posted an issue here.  Also it'd be nice to have the extension enabled when it detects a build.gradle file and you have the wrapper disabled. Good first issue?

**Comment by CsCherrYY** [comment]
We have fixed this bug in `3.7.0`. Could you please try again?

**Comment by brendansailer** [comment]
@CsCherrYY  I just upgraded to 3.7.0 and it works!  However it causes an error in another extension: "Cannot activate the 'Spotless Gradle' extension because it depends on an unknown 'richardwillis.vscode-gradle' extension."  Is this a problem with Spotless Gradle needing to update to 'microsoft.vscode-gradle'?

Also, if we disable the gradle wrapper the extension should still be active and appear even without a gradlew or gradlew.bat file.  Is this something you have planned to implement?

**Comment by CsCherrYY** [comment]
> Is this a problem with Spotless Gradle needing to update to 'microsoft.vscode-gradle'?

Yes. @badsyntax has a plan to update the `Spotless Gradle` extension, which will include this change.

> Also, if we disable the gradle wrapper the extension should still be active and appear even without a gradlew or gradlew.bat file. Is this something you have planned to implement?

A perfect suggestion. Let's make it in the improvement plan.

**Comment by CsCherrYY** [comment]
@brendansailer I see a new version of `Spotless Gradle` has been released, and the issue you mentioned seems to be fixed already. Could you have a try?

**Comment by brendansailer** [comment]
@CsCherrYY Yup the issue I mentioned is fixed in Spotless Gradle - my apologizes for not updating my comment.

Thanks for adding it to the improvement plan that is great! My experience with vscode extensions is limited, but I don't think it'd be super hard to implement and it would be a big improvement.  I feel like many users aren't aware you need a gradlew or gradlew.bat file for the extension to work.

**Comment by CsCherrYY** [comment]
verified in #1048
