### ISSUE TITLE
Using local Gradle install doesn't find any tasks

### ISSUE THREAD

**Issue by brendansailer** [badsyntax/vscode-gradle#1025]
Extension Name: vscode-gradle
Extension Version: 3.7.1
OS Version: Centos 7
VSCode version: 1.54.3

**Describe the bug**
When I disable the gradle wrapper and use a local version of gradle, the extension doesn't find any tasks.  I have limited experience with the gradle wrapper but I have a basic gradlew file in my project's repo to make this extension's tab appear in the activity bar.  Currently my gradlew file is just the default one, so that could be my problem if you need a more complex one to make the extension work.  I won't need to have a gradlew file here soon thanks to #1004 and I'm happy to help test it once that's implemented :)

I've tried changing "java.import.gradle.home" to values like "/opt/gradle/5.6.4" and "/opt/gradle/5.6.4/bin" but they all give me an error (see output below) so I'm fairly confident that I'm using the right value for that setting.
```
[error] [gradle-server] java.import.gradle.home is invalid, please check it again.
[error] Error running build: gradle runStart: java.import.gradle.home is invalid, please check it again.
```

**To Reproduce**
Using these settings, no tasks appear:
```
    "java.home": "/opt/jdk/jdk11",
    "java.import.gradle.enabled": true,
    "java.import.gradle.wrapper.enabled": false,
    "java.import.gradle.home": "/opt/gradle/5.6.4/bin/gradle",
    "java.import.gradle.user.home": "/home/brendan/.gradle",
    "gradle.autoDetect": "off",
```

**Expected behavior**
View available tasks under the tasks bar

**Output from "Gradle Tasks"**
```
[info] Found 0 tasks
[info] [gradle-server] Server started, listening on 45824
[info] Gradle client connected to server
[info] Found 0 tasks
[info] Found 0 tasks
[info] Found 0 tasks
```

**Does the bug still exist if you disable all other extensions?**
Yes

Thank you for the help! I'm working with my team to switch to vscode and having this extension working for our use case would be great!

**Comment by CsCherrYY** [comment]
Could you set `gradle.autoDetect` to `on` and try to specific `java.import.gradle.home` to `/opt/gradle/5.6.4` again?

**Comment by brendansailer** [comment]
Sure! I just tried those settings and am getting the error:
```
[info] [gradle-server] Server started, listening on 43023
[info] Gradle client connected to server
[error] [gradle-server] java.import.gradle.home is invalid, please check it again.
[error] Error getting build for /home/brendan/projects/git/project: java.import.gradle.home is invalid, please check it again.
[info] Found 0 tasks
[error] [gradle-server] java.import.gradle.home is invalid, please check it again.
[error] Error getting build for /home/brendan/projects/git/project: java.import.gradle.home is invalid, please check it again.
[info] Found 0 tasks
```
I looks like setting autoDetect to on makes it error out immediately and when I click the extension's tab it throws another one.  Is there something else I can try?  Thanks again for your help!

**Comment by CsCherrYY** [comment]
These logs will show only when `java.import.gradle.home` setting is **empty** (not invalid). Since you're confident with these settings, maybe it's related the environment (are you using it in remote environment?), BTW, could you provide a sample project to help me reproduce this issue in my PC?

A workaround is to specific `java.import.gradle.version` and keep `java.import.gradle.wrapper.enabled` with `false` if you really need a gradle distribution in `5.6.4`.

**Comment by brendansailer** [comment]
Great catch - I agree it's likely due to the environment as I've posted a few similar issues on other Gradle related plugins and they can't reproduce them either.  I develop within a VM that has limited network access and I don't use the Gradle wrapper, so I've been running into lots of weird bugs since that's a unique setup.  I'll create a sample project that has this issue this weekend and tag you once it's created.  I really appreciate the help :)

**Comment by brendansailer** [comment]
I updated my extension version to `3.9.0` and I no longer get the invalid `java.import.gradle.home` message! Here's what I have now in my settings:

```
    "java.home": "/opt/jdk/jdk11",
    "java.import.gradle.offline.enabled": true,
    "java.import.gradle.wrapper.enabled": false,
    "java.import.gradle.home": "/opt/gradle/5.6.4",
```

I only got this to work after some tweaking with the settings (due to the weird network and remote environment I work in).

@CsCherrYY  Feel free to close the issue 👍

**Comment by CsCherrYY** [comment]
Actually, the newest release seems not to address any issue about your problem, maybe some previous versions?

Anyway, very glad to see your problem has been solved🙂. Here I will close this issue since I can't do anything about this now. If you have any other findings, feel free to reopen this.
