### ISSUE TITLE
More convenient ways to create a new gradle project

### ISSUE THREAD

**Issue by Brettb-gpu** [badsyntax/vscode-gradle#1027]
Visual Studio Code is where I spend all my time programming, especially in Java, and its extensions have provided great support for the language. I use Gradle almost exclusively for building my Java projects, however, in the past creating new Gradle projects hasn't been the easiest since the `Java: Create Java Project` task has never provided support for Gradle, nor has any other method as far as I am aware of. I think a great addition to the Gradle Tasks extension would be providing support right out of the box for creating Gradle projects. Thank you!

**Comment by brendansailer** [comment]
I'm very new to Gradle (so I could be incorrect), but is gradle init insufficient?  It appears that gradle init could serve that purpose by having a button pop up in the gradle tasks window to call gradle init when the directory is empty?

**Comment by CsCherrYY** [comment]
I'll investigate if we can integrate `gradle init` with some manual steps in VSCode by some components such as quickpicks. 

> but is gradle init insufficient?

It's sufficient. Even if we can't integrate it, we can still add some convenient ways (like what @brendansailer mentioned) to avoid opening a standalone terminal and printing `gradle init`.

**Comment by Brettb-gpu** [comment]
It would be great if for example Gradle was listed as one of the build tool options under `Java: Create Java Project...`, which currently lists "No build tools", "Maven", "Spring Boot", "Quarkus", and "MicroProfile". `gradle init` is sufficient but it would be nice to have more convenient ways like what I proposed or others.

**Comment by CsCherrYY** [comment]
we can set parameters from `init` task. the examples can be found here: https://docs.gradle.org/current/userguide/build_init_plugin.html#sec:what_to_set_up
