### ISSUE TITLE
Parallel runnning of  gradle task

### ISSUE THREAD

**Issue by hannah23280** [badsyntax/vscode-gradle#1045]
VSCode: v1.61.0
vscode-gradle: v3.8.0

In view of current trend towards cloud and microservice, developer might need to run multiple instances of the same microservice application in the development machine to simulate replicas, 
Currently, when i execute a gradle task to run the application via vscode-gradle, the play button become stop button. if i have to run another new instance, i have to click the stop button in order to stop the current running instance, This implies that there is no way to go thru vscode-gradle to run multiple instances of the same application concurrently.

Hence, hope to request to allow parallel running of same gradle task concurrently, similar to what Intellij can do.
For more details on how intellij does this,  refer to https://github.com/microsoft/vscode-gradle/issues/798 .
In view that microsoft has currently taken over to maintain this extension, hence i open this new feature request .

**Comment by CsCherrYY** [comment]
Hi @hanct , I have started to support this feature. IMO https://github.com/microsoft/vscode-gradle/issues/798#issuecomment-734839964 makes sense overall, but some small questions:

- Do you need specify `org.gradle.parallel=true` in your properties file first? If not, the Gradle execute tasks one by one actually. (Although you can start more than one tasks at the same time)
- This behavior might be related to the setting `gradle.reuseTerminals`. If this setting is set to `all` or `task`, the default behavior is to use the previous terminal, so which is better in your mind:

  1. rerun the same task is only available when `gradle.reuseTerminals` is `off`
  2. always create a new terminal when run the same task, regardless of `gradle.reuseTerminals`
  3. add a new setting called something like `gradle.allowParallelRun` to control the behavior, if ture, follow ii.

**Comment by hannah23280** [comment]
Hi. Thanks for the support of this feature!
I am curious, is org.gradle.parallel similar to the requested feature?
Cos my initial request is about allowing us to run the same gradle task more than once, via the gradle GUI. 
Say, I click on  the run button beside  "bootRun" gradle task (provided by spring boot ) to run an application.  While the app instance is still running, a few seconds later, I would want to start another instance of the same application again via the GUI. Currently i can't do that , cos the Run button will change to "Stop button", when the first instance is runned

This is equivalent to ,me, opening 2 command prompt. Each running the command line **gradle bootRun** on the same application. Is that equivalent to parallel feature in gradle?

**Comment by hannah23280** [comment]
So my initial thinking is, once we click on the Run button, the Run button remain as it is, so that we can click on it to trigger another execution of the same task.  Hopefully there can be a number indicator beside the Run button to indicate how many instances of this gradle task are currently still in execution.

**Comment by CsCherrYY** [comment]
got it. I'll add a new configuration to control this behavior (it will be disabled by default, but you can enable it for your case). 

> Hopefully there can be a number indicator beside the Run button to indicate how many instances of this gradle task are currently still in execution.

Not sure if it's very helpful and feasible:

- You can easily find the instances via terminal panels since the terminal's title is the task's name
- I'm not sure the description is the proper place to put the number (it works only for this case)

So my suggestion is to waiting for the feedbacks of this feature. I'll update here once the PR has been created.

**Comment by CsCherrYY** [comment]
@hanct #1122 will fix this issue, and could you try https://github.com/CsCherrYY/vscode-test/blob/main/vscode-gradle-3.8.4.vsix to see if this works in your scenario? You can set `gradle.allowParallelRun` to `true` and `gradle.reuseTerminals` to `off` to enable this feature.

**Comment by hannah23280** [comment]
> got it. I'll add a new configuration to control this behavior (it will be disabled by default, but you can enable it for your case). 
> 
> > Hopefully there can be a number indicator beside the Run button to indicate how many instances of this gradle task are currently still in execution.
> 
> Not sure if it's very helpful and feasible:
> 
> - You can easily find the instances via terminal panels since the terminal's title is the task's name
> - I'm not sure the description is the proper place to put the number (it works only for this case)
> 
> So my suggestion is to waiting for the feedbacks of this feature. I'll update here once the PR has been created.

Noted. Agree to wait for feedback for the number indicator. Thanks!

**Comment by hannah23280** [comment]
By the way, I presume the debug also works the same. We can click on debug button multiple times, to run application (in debug mode) in multiple instances.

**Comment by CsCherrYY** [comment]
@hanct I think https://github.com/microsoft/vscode-gradle/pull/1122/commits/495d08c697f73ea4b60ddbd4f982c7b6855bf37e solves this problem.

![Screenshot](https://user-images.githubusercontent.com/45906942/146293118-2aa4f096-d272-402f-af7f-f318bf6209f5.png)
