### ISSUE TITLE
Build Task in the root gradle project does not get displayed 

### ISSUE THREAD

**Issue by hannah23280** [badsyntax/vscode-gradle#1046]
Extension Name: vscode-gradle
Extension Version: 3.8.0
OS Version: Windows
VSCode version: 1.61.0

I am developing a gradle-based project, which has nested gradle projects (namely, mainservice and mainservice1), as shown in the below screenshot.  I notice that the root gradle project (csv_bundler) does not have a task called build. But yet, i can go to the command prompt and execute gradlew.bat build at the root project.  

![image](https://user-images.githubusercontent.com/4410920/99880431-36006980-2c4e-11eb-96f3-e2ae39fe17ee.png)

When i execute the gradlew.bat tasks at the root project, the terminal list down all the supported tasks , one of them include build task. But yet  in the gradle pane, build task (among others) does not get displayed.
![image](https://user-images.githubusercontent.com/4410920/99880376-f5085500-2c4d-11eb-948f-cd3af4f38db4.png)

For more detail, refer to a previously open request  on https://github.com/microsoft/vscode-gradle/issues/794 .
I open a new one, cos the the previously open request is created before microsoft takes over.

**Comment by mozhuanzuojing** [comment]
@hanct `build` It is provided by the `java` plugin. If the root project does not apply the plugin, there will be no.
.

**Comment by hannah23280** [comment]
> @hanct `build` It is provided by the `java` plugin. If the root project does not apply the plugin, there will be no. .

Thanks for the hint. Unfortunately, I can't apply java plugin at root level, as there will be error during building. I think cos root level does not have any expected source codes. So i have no choice but to remove apply java plugin at root level, after which the build is successful

**Comment by CsCherrYY** [comment]
@hanct Sorry for the late reply since we just finished the release of version 3.8.1.

After reading your comments and discussion in #794, and tried myself (both in current mechanism and by a separate Gradle plugin), I'm convinced the root project doesn't contain such Build tasks.

But you can still run the tasks under `Build` category correctly in Gradle CLI or other tooling in the project root, IMO it's from [Gradle execute tasks mechanism](https://docs.gradle.org/current/userguide/intro_multi_project_builds.html#sec:executing_tasks_by_name). Each build task you execute in the root project will tell all the tasks with the same name in subprojects to execure, which makes them "available" or "runnable" in the root project. That's why they are shown in both `Gradle tasks` CLI and IntelliJ explorer.

**Comment by hannah23280** [comment]
> @hanct Sorry for the late reply since we just finished the release of version 3.8.1.
> 
> After reading your comments and discussion in #794, and tried myself (both in current mechanism and by a separate Gradle plugin), I'm convinced the root project doesn't contain such Build tasks.
> 
> But you can still run the tasks under `Build` category correctly in Gradle CLI or other tooling in the project root, IMO it's from [Gradle execute tasks mechanism](https://docs.gradle.org/current/userguide/intro_multi_project_builds.html#sec:executing_tasks_by_name). Each build task you execute in the root project will tell all the tasks with the same name in subprojects to execure, which makes them "available" or "runnable" in the root project. That's why they are shown in both `Gradle tasks` CLI and IntelliJ explorer.

@CsCherrYY Hi, thanks for the response. Since "gradle tasks" can returns all the tasks, will it possible to enhance the vscode-gradle, where the root project (that contains subprojects), is able to display all the tasks from the command "gradle tasks".  So that developer can just double click on a task under the root project, in order for it to run all tasks with the same name in subprojects.

Reason for such enhancement is because for root projects with many subprojects, it would be very tedious to build/run them individually. Of course, we can run them via CLI, but I thought one benefit of using vscode-gradle extension is to shield us away from typing command line, and instead provide simple click of interface to run gradle tasks.

**Comment by CsCherrYY** [comment]
Agree with that we should keep alignment with the command "gradle tasks". Let me investigate first and find a better way to implement it.
