### ISSUE TITLE
Minor patch version of Java makes Gradle Extension not work

### ISSUE THREAD

**Issue by marketspider** [badsyntax/vscode-gradle#1077]
Extension Name: vscode-gradle
Extension Version: 3.8.2
OS Version: Ubuntu 20.04
VSCode version: 1.61.2
Java version: Openjdk 16.0.1
Gradle version: 7.2

**Describe the bug**
Originally, the combination of Java 16.0.1 and Gradle 7.2 should work, but as shown in the attached screenshot, it is determined to be a version higher than Java 16.

**To Reproduce**
The combination of Openjdk 16.0.1 and Gradle 7.2 and Gradle for Java Extension 3.8.2.

**Screenshots**
![image](https://user-images.githubusercontent.com/53471950/140460101-51dd598e-7592-4d05-b8b0-8b5778656f49.png)

**Output from "Gradle for Java"**
```
[info] Java Home: /usr/lib/jvm/java-16-openjdk-amd64
...
[info] Gradle Version: 7.2
[error] [gradle-server] Could not fetch model of type 'GradleProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-7.2-bin.zip'.
[error] Error getting build for /home/asano/ideaproject: Could not fetch model of type 'GradleProject' using Gradle distribution 'https://services.gradle.org/distributions/gradle-7.2-bin.zip'.
```

**Comment by mozhuanzuojing** [comment]
@marketspider could you share your settings.xml and your project

**Comment by marketspider** [comment]
+ Don't work
```
{
  "java.home": "/usr/lib/jvm/java-16-openjdk-amd64",
  "java.import.gradle.jvmArguments": "-XX:+UseParallelGC -Xmx4G",
  "gradle.debug": true
}
```

1.  Worked fine. 
```
{
  "java.home": "/usr/lib/jvm/java-16-openjdk-amd64",
  "gradle.debug": true
}
```
2.  Worked fine.
```
{
  "java.home": "/usr/lib/jvm/java-16-openjdk-amd64",
  "java.import.gradle.jvmArguments": "-Xmx4G",
  "gradle.debug": true
}
```
3.  Worked fine.
```
{
  "java.home": "/usr/lib/jvm/java-16-openjdk-amd64",
  "java.import.gradle.jvmArguments": "-XX:+UseParallelGC",
  "gradle.debug": true
}
```

I apologize, it worked fine when I specified either no jvmArguments or one jvmArguments at a time.
However, when two jvmArguments are specified, it does not work.

**Comment by marketspider** [comment]
My project is a Gradle multiple subproject template.
![image](https://user-images.githubusercontent.com/53471950/140467703-abd032c5-1bf8-401a-beac-1139c0cfa74b.png)

This is generated by the following command.
gradle init -> application -> Java -> multiple subproject -> groovy

**Comment by CsCherrYY** [comment]
Thanks for reporting. Actually, there are two issues:
- Should check major Java version only when compatibility checking.
- Our extension accepts `java.import.gradle.jvmArguments`, but there is a bug when parsing the setting: More than one argument is not supported. I have found the root cause of this bug and will fix it soon.
