### ISSUE TITLE
Gradle Server fails to start; WSL

### ISSUE THREAD

**Issue by chozandrias76** [badsyntax/vscode-gradle#1093]
Extension Name: vscode-gradle
Extension Version: newest as of 11/4/2021, 24:56:25
OS Version: Windows 10.00.22000.0001 x64
VSCode version: 1.62.2

**Describe the bug**
Cannot launch Gradle Server due to Java not being found

**To Reproduce**
- Install Java using Choco for Windows or using SDKMAN in WSL
- Create a new project in WSL with VSCode
- Install the Gradle Extension
- Update settings.json to include path echoed from `whence java` or `where java`
- Gradle server fails to start

**Expected behavior**
Gradle starts and throws no errors

**Screenshots**
![image](https://user-images.githubusercontent.com/2087677/142744244-b6f965de-a6ae-412c-ac21-284def5f7603.png)

**Output from "Gradle for Java"**
```
[debug] [gradle-server] Starting server
[debug] [gradle-server] Gradle Server cmd: c:\Users\swens\.vscode\extensions\vscjava.vscode-gradle-3.8.2\lib\gradle-server.bat 57074
[info] [gradle-server] ERROR: JAVA_HOME is set to an invalid directory: /home/banon/.sdkman/candidates/java/current/bin/java
[info] [gradle-server] Please set the JAVA_HOME variable in your environment to match the
[info] [gradle-server] location of your Java installation.
[warn] [gradle-server] Gradle server stopped
[error] Error connecting to gradle server: The channel has been closed
[error] The client has state: SHUTDOWN
[debug] [gradle-server] Starting server
[debug] [gradle-server] Gradle Server cmd: c:\Users\swens\.vscode\extensions\vscjava.vscode-gradle-3.8.2\lib\gradle-server.bat 61970
[info] [gradle-server] ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\OpenJDK\jdk-17.0.1\bin
[info] [gradle-server] Please set the JAVA_HOME variable in your environment to match the
[info] [gradle-server] location of your Java installation.
[warn] [gradle-server] Gradle server stopped
[error] Error connecting to gradle server: The channel has been closed
[error] The client has state: SHUTDOWN
```

**Does the bug still exist if you disable all other extensions?**
Yes

**Additional context**

**Comment by CsCherrYY** [comment]
setting `java.home` should be set to the root path of a jdk. In your case, please try `C:\Program Files\OpenJDK\jdk-17.0.1`.

**Comment by chozandrias76** [comment]
Thanks, that resolved it.
