### ISSUE TITLE
Working example with task debugging?

### ISSUE THREAD

**Issue by dboreham** [badsyntax/vscode-gradle#1118]
I'm a few hours into trying to make gradle task debugging (as described [here](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle) and [here](https://stackoverflow.com/questions/63645177/vscode-gradle-java-run-and-debug)) to work. I'm using a project generated with `gradle init`. The "bug" icon stubbornly refuses to appear. 

I feel like I'm staring at a 1000-light christmas tree, wondering which bulb needs to be replaced to get the thing to light up :(

It would be great to have a known working example (e.g. a repo in github) that could be used as a reference when trying to diagnose problems like this.

I've created a repo with the stock `gradle init` generated project. When I load this into VSCode on Windows using WSL2, with the Java Language, Java Debug, Kotlin and Gradle extensions, no debug icon appears : https://github.com/dboreham/vscode-gradle-debug-nowork

![image](https://user-images.githubusercontent.com/1649760/145158199-f7716974-7244-48e1-a9b2-9f854c88884e.png)

fwiw I am attempting to prove that VSCode is usable for Kotlin development in a heavily IntelliJ-oriented shop.

**Comment by dboreham** [comment]
I'm beginning to suspect that this just doesn't work. Some additional testing I've done:

1. Try using Java, not Kotlin (still doesn't work).
2. Try running on Windows rather than WSL2 (same result).
3. Try global search of github for `gradle.javaDebug`. This led me to this repo: https://github.com/praktikum-tiunpad-2021/oop-javafx-example which also doesn't work (no debug icon on the run task), even though it has an apparently manually created debug config in settings.json.

**Comment by dboreham** [comment]
After some head-scratching around how to debug an extension running in WSL2, I was able to diagnose this.

The code [here](https://github.com/microsoft/vscode-gradle/blob/57f7b8b948cb28db8f32cebcf6a019c9a5f60e9d/extension/src/views/viewUtil.ts#L132) tests whether the "script" name is included in the set defined for debugging. When I put a breakpoint on that code, I discovered that `script` never equals "run". It does have the value "app:run", and when I added that to the debug task list in `settings.json` lo and behold the bug icon appears.

To the best of my knowledge, the text "app:run" appears nowhere : not in the extension UI tree view, and not in the output from `gradle tasks`, so the user would have no clue to enter it as a debug task.

![image](https://user-images.githubusercontent.com/1649760/145279016-a1689b55-52f0-4cf9-b56f-d2cf9e409f28.png)

**Comment by dboreham** [comment]
I found another project (the large real project I work on, not a small test project) where the stock "run", "test" debug config works as expected. This project is nested. I'm not sure if that's significant. So the debug/no-debug syndrome has something to do with how gradle tasks are named it seems, although the output from `gradle tasks` indicates they're not named differently.

**Comment by badsyntax** [comment]
hi @CsCherrYY fyi my vision for this was to use a gradle plugin (via init script) to automatically discover tasks of type `JavaExec`, so that users wouldn't need to manually supply the debuggable tasks. 

i took a stab at this a while ago with https://github.com/microsoft/vscode-gradle/pull/398 but had some issues and had to abandon it. it would be a great UX if you can do something similar to my original plan 

see also https://github.com/microsoft/vscode-gradle/issues/394

**Comment by CsCherrYY** [comment]
@badsyntax Thanks for the information, the current UX (manually to add tasks) is not smooth indeed. We now use the Gradle plugin to get some build information for language-server. I think it's the correct way and we can add some logic into that plugin.

**Comment by CsCherrYY** [comment]
#1149 will support to automatically detect "debuggable" tasks and no settings are needed to specify any more.

**Comment by CsCherrYY** [comment]
fixed via #1149
