### ISSUE TITLE
support test-sharing module

### ISSUE THREAD

**Issue by nospam06** [badsyntax/vscode-gradle#1154]
Extension Name: vscode-gradle
Extension Version:
OS Version:
VSCode version:

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Output from "Gradle for Java"**
You can find this by clicking on the "Output" panel, then selecting the "Gradle for Java" channel from the dropdown.

**Does the bug still exist if you disable all other extensions?**
Yes/No

**Additional context**

**Comment by CsCherrYY** [comment]
could you provide any details, examples or introductions?

**Comment by nospam06** [comment]
https://github.com/nospam06/gradleSample
vscode cannot open this project. i have test sharing modules to instantiate spring beans. both intellij and gradle command line can do the build correctly
[{
	"resource": "/home/ling/source/gradleSample/app",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": "1001",
	"severity": 8,
	"message": "One or more cycles were detected in the build path of project 'app'. The paths towards the cycle and cycle are:\napp->{test-share, business-logic}\napp->{test-share, business-logic, utilities}\napp, test-share->{business-logic, utilities}",
	"source": "Java",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

**Comment by nospam06** [comment]
@CsCherrYY

**Comment by CsCherrYY** [comment]
@nospam06 get it, I'll take a look

**Comment by nospam06** [comment]
gradle has testFixture to accomplish sharing test code. Will close this issue.
