### ISSUE TITLE
recognizing generated source code in build/generated/sources/annotationProcessor/java

### ISSUE THREAD

**Issue by leeyc0** [badsyntax/vscode-gradle#1164]
I am using AutoValue (https://github.com/google/auto) code generator, but found that the source code in build/generated/sources/annotationProcessor/java is not picked up automatically. I have to configure the project with this

```
sourceSets {
    main {
        java {
            srcDir tasks['compileJava'].options.generatedSourceOutputDirectory.getAsFile().get()
        }
    }
    test {
        java {
            srcDir tasks['compileTestJava'].options.generatedSourceOutputDirectory.getAsFile().get()
        }
    }
}
```
to let vscode pick up the generated code, otherwise there will be unresolved class error:

```
@AutoValue
abstract class CsvRowTest implements Serializable {
    @SchemaCreate
    public static CsvRowTest create(String a, String b) {
       // the class AutoValue_CsvRowTest is generated automatically into build/generated/sources/annotationProcessor/java
       // not picking up this directory will cause this class unresolved.
       return new AutoValue_CsvRowTest(a, b);
    }
    
    public abstract String getA();
    public abstract String getB();
}
```

Is it possible to have vscode-gradle to pick up the directory build/generated/sources/annotationProcessor/java automatically?

**Comment by CsCherrYY** [comment]
I think the unresolved class error you mentioned is reported by redhat.java extension, repository: https://github.com/redhat-developer/vscode-java. vscode-gradle will not report any error in Java files, but Gradle files.

If I'm guessing right, I suggest you open an issue in the above repository to discuss this issue. FYI the vscode-gradle project also uses the similar mechanism to solve this issue, see: https://github.com/microsoft/vscode-gradle/blob/bba4bfffa690a45f804d76058cc8a5a7ad5e985b/gradle-server/build.gradle#L38-L42

**Comment by leeyc0** [comment]
Thanks. I must be somehow brain-dead, mistaking the two repositories. Also there is actually active issues about this.
