### ISSUE TITLE
run debuggable tasks always start debugging it

### ISSUE THREAD

**Issue by CsCherrYY** [badsyntax/vscode-gradle#1181]
Running a task that can be debugged will always trigger debug session, not just running it.

**Comment by CsCherrYY** [comment]
verify steps:

1. git glone https://github.com/spring-projects/spring-petclinic
2. open VSCode
3. add a breakpoint at line 53, PetClinicIntegrationTests.java or any other test method.
4. run task `verification/test`, you can see the breakpoint will not be hit
5. debug task `verification/test`, you can see the breakpoint will be hit

**Comment by Eskibear** [comment]
verified, and it works as expected. 

One minor issue related to UX, see if there's room to improve. When debugging, it runs corresponding gradle task in terminal, but when debug session is attached, it opens debug console and debug view, and I lose focus of the terminal, which might be not good enough for users not familiar with vscode. As debug console provides no extra information, and it takes me time to get back to terminal.

**Comment by CsCherrYY** [comment]
I think there is some information in your debug console, e.g., "different debugger and debuggee JDK version". The new message will reveal the debug console. If there is no debug console message, the terminal will always be at the front during debugging.
