### ISSUE TITLE
Move the Pinned Task to another section

### ISSUE THREAD

**Issue by hannah23280** [badsyntax/vscode-gradle#1197]
Hi,

I recall last time, there used to be a "bookmark" section which contains bookmarked task. But now its gone, and seem to be replaced with "Pinned Task".

However, pinned task appear under the specific gradle project.  So if i have multiple gradle projects, and each gradle project contain a pinned task.   If i now wanted to execute the pinned task under each gradle project, i have to expand each of the gradle project , then expand  the "Pinned Task" and click the pinned task. Quite tedious actually. 

but if all the pinned tasks gather under one "bookmark" section, it is easier to click them one by one.

Just a 10cent worth of suggestion.

**Comment by CsCherrYY** [comment]
Thanks for reporting. Actually, the reason we remove the **pinned tasks** view is to reduce the number of views, the target in long-term is to remove the Gradle Side Bar and make Gradle a single view like `Java Projects` or `Maven`. 

Come back to your request, IMO it's reasonable. One approach is to provide a setting, to control whether to show the pinned tasks in each project (current behavior) or in a specific pinned tasks group item under the `Gradle projects` view (what you want). Does it make sense?

**Comment by hannah23280** [comment]
Yes  make sense 
I like your idea of " specific pinned tasks group item under the Gradle projects view".  Also, can consider putting the pinned group item  at the top, instead of below all the Gradle projects, from usability perspective 

By removing the sidebar, I assume that mean in long term, Gradle view would be under the explorer view, such that gradle and java projects can be viewed together. This is great idea! 
  But then what abt the recent tasks  and gradle daemon sections in the current Gradle sidebar?

**Comment by CsCherrYY** [comment]
> But then what abt the recent tasks and gradle daemon sections in the current Gradle sidebar?

The draft for the recent tasks view is to use a quickpick list, you can choose the recent run task and reveal in the Gradle projects view. For daemon sections, Actually few users are using them so it might be a quickpick list as well? Could you provide any suggestions?

For this request, I'll add the pinned group in the next release.

**Comment by hannah23280** [comment]
If using quickpick, that would mean in future no more graphical UI to mouse click, and mainly rely on keyboard typing to trigger them. 
For me,  cos I rarely use them, so i thought should be ok to be in quickpick list.
Hopefully those few users who use them can comment on this change.

**Comment by CsCherrYY** [comment]
@hanct #1205 will solve this issue. Could you please go to that PR and check if the ux looks good to you?

**Comment by hannah23280** [comment]
> @hanct #1205 will solve this issue. Could you please go to that PR and check if the ux looks good to you?

Look fantastic to me . Love it!
I like the pinned tasks at global level , easy to access at the top. Thanks!
And yeah, it definitely looks good to me.
