### ISSUE TITLE
`Gradle for Java(Language Server)` Chinese garbled

### ISSUE THREAD

**Issue by mozhuanzuojing** [badsyntax/vscode-gradle#1208]
Extension Name: vscode-gradle
Extension Version: 3.11.0
OS Version: windows 11
VSCode version: 1.66.1

**Describe the bug**
log of `Gradle for Java(Language Server)`  exists Chinese garbled.

**To Reproduce**
1. git clone https://gitee.com/mozhuanzuojing/gradle-jdeps.git
2. open `gradle-jdeps`, and wait build finishd.
3. open file `build.gradle`
4. open `Gradle for Java(Language Server)` from `OUTPUT`
5. `F1`  exec  `Java: Clean Java Language Server Workspace`  and `Restart and delete`.
6. please notice `Gradle for Java(Language Server)` of `OUTPUT`.

**Expected behavior**
Chinese display is correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/63572041/162610861-5863dbf5-456d-49b6-9456-7be31f0e7ab0.png)

**Output from "Gradle for Java(Language Server)"**
```log 
4�� 10, 2022 4:53:44 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 1
4�� 10, 2022 4:53:44 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
����: Unmatched cancel notification for request id 2
```

**Does the bug still exist if you disable all other extensions?**
No

**Additional context**
This problem has always been there and can now be reproduced with the minimal project above.

**Comment by CsCherrYY** [comment]
I can reproduce this issue and am investigating how to solve it.

**Comment by CsCherrYY** [comment]
@mozhuanzuojing We have fixed it in the pre-release version `3.12.2022042706`. You can try it via switch to Pre-Release version:

![image](https://user-images.githubusercontent.com/45906942/165458627-9b92a8e0-825e-4d74-abec-2568b05dd46d.png)

**Comment by mozhuanzuojing** [comment]
@CsCherrYY Thanks for your contribution, it worked.

**Comment by nickzhums** [comment]
thanks, it also worked for me
