### ISSUE TITLE
No Connection to gradle server. Try restarting the server (Gradle for Java)

### ISSUE THREAD

**Issue by VWMN** [badsyntax/vscode-gradle#1221]
Extension Name: Gradle for Java
Extension Version: v3.12.0 
OS Version: Macos Monterey 12.3.1
VSCode version: 1.67.0 (Universal)

![Screen Shot 2022-05-10 at 15 08 22](https://user-images.githubusercontent.com/104971237/167580564-06361dde-993d-4f6f-b524-4fb0aca75149.png)
![Screen Shot 2022-05-10 at 15 10 40](https://user-images.githubusercontent.com/104971237/167580962-4f184ed9-04dd-4888-9227-88243975486d.png)

**Output from "Gradle for Java"**
[Error - 1:38:47 PM] Starting client failed
Launching server using command /Library/Java/JavaVirtualMachines/bin/java failed.

**Additional context**
I've tried to restart the server, my device, and reinstall vscode

**Comment by CsCherrYY** [comment]
The dir `/Library/Java/JavaVirtualMachines/bin/java` is your JDK path or not?

**Comment by VWMN** [comment]
> The dir `/Library/Java/JavaVirtualMachines/bin/java` is your JDK path or not?

yes

**Comment by VWMN** [comment]
but
![Screen Shot 2022-05-10 at 15 26 54](https://user-images.githubusercontent.com/104971237/167584290-e65c5e09-05c4-45dd-8d03-53670b5465d6.png)

I have Zulu-17.JDK

**Comment by CsCherrYY** [comment]
This page shows your given path `/Library/Java/JavaVirtualMachines` is not a valid JDK and it's provided by vscode-java-pack, so our tools can't use this java home to import your project. You can set `java.home` to another JDK or just remove `java.home` setting in `settings.json` since it has been deprecated.

**Comment by VWMN** [comment]
thanks it work!
