### ISSUE TITLE
Task and its pinned version not synchronized

### ISSUE THREAD

**Issue by hannah23280** [badsyntax/vscode-gradle#1245]
Extension Name: vscode-gradle
Extension Version: v3.12.2
OS Version: Windows
VSCode version: v1.68.1

**Describe the bug**
Task and its pinned version 's running status not synchronized
![image](https://user-images.githubusercontent.com/4410920/177727055-9d21652b-ff9b-42c1-bebc-50eee908edca.png)

**To Reproduce**
1) In the gradle explorer, pin a task.
2)  Run the task (not its pinned)
3) You see that the task is currently running with the stop button beside it.  But its pinned version does not show that it is currently running

**Expected behavior**
Both the task and its pinned version should show the same running/stopping status.

**Comment by hannah23280** [comment]
I not sure if this is considered a bug, or meant to be like this.

When I click on the play button in the pinned task,  the play button beside this pinned task remain as play button, but its actual task play button become stop button, which indicates it is running.

**Comment by CsCherrYY** [comment]
it should be consistent, I'll take a look.
