### ISSUE TITLE
Download Sources

### ISSUE THREAD

**Issue by himslm01** [badsyntax/vscode-gradle#1246]
**Is your feature request related to a problem? Please describe.**
I might be missing something, but I can't find a way to download sources of dependencies. A feature I've used a lot in other IDEs

**Describe the solution you'd like**
Have the ability to globally enable the downloading of sources for all dependencies.

**Describe alternatives you've considered**
Not found any practice work-arounds.

**Additional context**

**Comment by CsCherrYY** [comment]
could you paste your output log in "Gradle for Java" channel? is your PC using proxy?

**Comment by quanzhuo** [comment]
This is a must have feature. 

When jump into method in dependency jar. vscode-gradle just decompile the class file to show the source code. No document present in the decompiled source code which is very inconvenient.

In IDEA, it will show a button to promopt to download source jars and jump into source file. This is a great feature

**Comment by robaho** [comment]
Or at least make 'Attach Sources...' work when using Gradle.

**Comment by mamilic** [comment]
Hi @jdneo, I was wondering is the amount of work for this enhancemnet somewhat reasonable and in scope for this project? If that is the case, could you give me some hints where to start? 🙌

**Comment by jdneo** [comment]
@mamilic could you reproduce this issue?

**Comment by mamilic** [comment]
@jdneo , it seems that I can not. As I can tell, at least on my PC it downloads the sources always. Is that default behavior?

**Comment by jdneo** [comment]
@mamilic It's a little complex to explain. I'll try to explain it clear.

So for the gradle project we have two importer, `gradle build server`and `buildship`:

_// If project is imported by `gradle build server`, the container name is displayed as `Referenced Libraries`
// If project is imported by `buildship`, the container name is displayed as `Project and External Dependencies`_

The source jars are always downloaded by `gradle build server`, in this case, users do not need to do anything and will see the sources.

If it's `buildship`, It's lazy-load approach. Which means, when user opens a class file and the source jar is not downloaded locally, a download task will be kicked. Once it's downloaded, next time user opens that file, he should be able to see the sources.

**Comment by jdneo** [comment]
I tend to close this issue right now. But if anyone finds that my understanding is incorrect, please leave comment here.
