### ISSUE TITLE
`JAVA_HOME` or `java.jdt.ls.java.home` should not be required for projects that don't develop Java code

### ISSUE THREAD

**Issue by tudortimi-ifx** [badsyntax/vscode-gradle#1249]
Extension Name: vscode-gradle
Extension Version: v3.12.2
OS Version: RHEL8
VSCode version: 1.62.2

**Describe the bug**
The extension complains about not finding a setting for `JAVA_HOME` or `java.jdt.ls.java.home`, even when it's not being used to develop Java code. The extension seems to partially work, though. No language server is started, but Gradle tasks can be executed.

**To Reproduce**
Start VS Code with extension installed without installing Java extension, without setting a `JAVA_HOME` environment variable (but with `java` in `PATH`.

**Expected behavior**
I would expect the extension to fall back on the system location for `java`, which is on `PATH`, like Gradle itself does, and not require `JAVA_HOME` or the Java VS Code extension. I see from #249 that this is what the extension used to do.

**Screenshots**
![image](https://user-images.githubusercontent.com/15451034/178245967-c685dfd2-0ec1-4a4e-809e-8ca8bf2925a9.png)

**Output from "Gradle for Java"**
Log showing that the system installation for Java is being taken, but I'm guessing this comes from Gradle, not from VS Code.
```
[info] [gradle-server] Server started, listening on 43861
[info] Gradle client connected to server
[info] Java Home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.322.b06-2.el8_4.x86_64
[info] JVM Args: -XX:MaxMetaspaceSize=256m,-XX:+HeapDumpOnOutOfMemoryError,-Xms256m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant
```

**Does the bug still exist if you disable all other extensions?**
Yes

**Comment by CsCherrYY** [comment]
Is there any gap if you set JAVA_HOME in your environment variable? AFAIK Gradle it self will adopt both the two configurations, but i'm not sure which has the higher priority (JAVA_HOME and PATH)

**Comment by tudortimi** [comment]
To make sure we're on the same page, the problem isn't with Gradle, but with the language server that the extension tries to start.

**Comment by tudortimi** [comment]
I can, of course, set `JAVA_HOME` to make it work. This means, though, that all other developers also need to set `JAVA_HOME` before starting VS Code. The extension could make life easy by trying to extract `JAVA_HOME` from the `java` executable that is on `PATH`, as it used to.

**Comment by tudortimi** [comment]
Also, my `java` executable on RHEL8 is `/bin/java`. To get the extension to work with this executable, I have to set `JAVA_HOME` to `/`, which looks very weird.

**Comment by CsCherrYY** [comment]
Get it. I'm going to let the language server pick the same config with Gradle.
