### ISSUE TITLE
Terminals' tab names to be different for different gradle projects under same workspace

### ISSUE THREAD

**Issue by hannah23280** [badsyntax/vscode-gradle#1250]
Hi,
  In the below screen, I have 2 gradle-based spring boot projects under same workspace. When i run the task bootRun for both via the gradle pane, i notice 2 terminals are opened.  So far, no issue.  But the 2 terminals are named exactly the same, hence i can't track which terminal is for which gradle project.   Hence would like to suggest  terminals names to reflect the gradle project names as well?
![image](https://user-images.githubusercontent.com/4410920/178432480-436304a9-5ef7-4f61-88b6-1bd970990c17.png)

**Comment by CsCherrYY** [comment]
It seems the extension will distinguish the label with workspace folder name, (in your screenshot, spring_boot_up_running), do you have 2 different projects under a workspace folder? could you please provide a sample?

**Comment by hannah23280** [comment]
In fact...I have many different gradle based projects. See screenshot - i have circled them in red
![image](https://user-images.githubusercontent.com/4410920/182382748-c6dc4d51-68ed-4d22-bb43-5804af9eca0c.png)

**Comment by CsCherrYY** [comment]
@hanct So all of them are the subprojects of project spring_boot_up_running?

**Comment by hannah23280** [comment]
They are NOT subprojects of  spring_boot_up_running. 
spring_boot_up_running is just a normal folder, to contain all my gradle based projects (aircraft-positions, aircraft-positions-messaging, etc). In other words, these gradle based projects are NOT related to one another. They just happen to be contained inside spring_boot_up_running,

![image](https://user-images.githubusercontent.com/4410920/182503806-fc21caec-fd44-4940-b73a-55ed09bcd7c5.png)

**Comment by CsCherrYY** [comment]
I know, so you're using `gradle.nestedProjects` to discover them?

**Comment by hannah23280** [comment]
Yes. Set as true

**Comment by CsCherrYY** [comment]
@hanct The task label you have seen is like the following format:
`${source}: ${name} (${workspaceFolder})`

It seems that the only thing we can do is add the relative folder information in the task name. I'm not sure if your case (using `gradle.nestedProjects` to find a bunch of unrelated projects) is such popular so I'm considering adding a configuration to make it better in your scenario. 

e.g., `gradle.taskLabel` controls the label scheme. The default value is `${script}`, the other option is `${script} (${relativePath})`, can show the relative path to the workspace folder in the brackets. In your case, it will look like `gradle: bootRun (aircraft-xxx) (spring_boot_up_running)`

Does it make sense?

**Comment by hannah23280** [comment]
Hi,
Thanks. Yes this label (gradle: bootRun (aircraft-xxx) (spring_boot_up_running)) is okay for me, although **gradle: bootRun  (spring_boot_up_running/aircraft-xxx)** would be better, cos less pairs of bracket , hence more soothing to eye.

**Comment by CsCherrYY** [comment]
> although gradle: bootRun (spring_boot_up_running/aircraft-xxx) would be better, cos less pairs of bracket , hence more soothing to eye.

Agree that would be better. But now `(spring_boot_up_running)` is the workspace folder name and controlled by VS code. The only part can be customized is the `${name}` I just mentioned :(

**Comment by CsCherrYY** [comment]
@hanct I'm drafting the PR #1265. 

As for adding the configuration, I prefer to keeping the current behavior, and if **duplicate** terminal tab detected, the extension will automatically add the relative path. WDYT?

**Comment by hannah23280** [comment]
That would actually mean when there is only one terminal, for my case, it would not be possible to know this terminal is from which project.  Nevertheless, I am okay with that.
Thanks!
