### ISSUE TITLE
Intermitten error "Failed to attach to remote debugee.."

### ISSUE THREAD

**Issue by hannah23280** [badsyntax/vscode-gradle#1258]
Extension Name: vscode-gradle
Extension Version: v3.12.2
OS Version: windows 10
VSCode version: 1.69.2
Vscode-java extension version: v1.9.0

**Describe the bug**
Clicking on the debug icon beside the task "bootRun"  intermittently throw error, as shown below
![image](https://user-images.githubusercontent.com/4410920/180632779-ea793cc1-3cc8-4ac8-9d3e-c1e31d67914f.png)

When this feature is first implemented, i never encounter such issue. 

Note that this is intermittent error...4 out of 5 times of debugging, this error will keep appearing each time i click the debug icon.

**Comment by NogrTL** [comment]
Same.
Goes away if you run task few time or tasks can start quickly..

My assumption it's something with 'debugger' timeouts

**Comment by hannah23280** [comment]
> Same.
> Goes away if you run task few time or tasks can start quickly..
> 
> My assumption it's something with 'debugger' timeouts

Thanks! I initially still thought I am the only one encountering this issue. 
 Pray hard this issue can be resolved fast.

**Comment by CsCherrYY** [comment]
The current timeout to wait the debugger to launch is 10s.
https://github.com/microsoft/vscode-gradle/blob/a3d41be8049d1f60ab251f404862fb4d2dcbd7b4/extension/src/util/index.ts#L11

Does this message appear within this timeout or after this timeout?

**Comment by hannah23280** [comment]
Hi, I have tested it out a few times. It appears within the timeout (approx around 6-7s)

**Comment by CsCherrYY** [comment]
@hanct Get it, emmm but I can't reproduce it locally. Could you provide a sample project? I'm guessing it's the bug about the current mechanism of querying debug port.

**Comment by hanct** [comment]
Noted. Will provide the sample project soon. Meanwhile, i have just updated my vscode to the latest version v1.70.0, and realize that now i could not even debug.  Below is what i see...It seem to hang down there indefinitely.  

![image](https://user-images.githubusercontent.com/4410920/183620009-cb98ed6e-1aa0-473f-876f-ec7809733370.png)

*Do note that the value 55011 is always changing.

**Comment by hannah23280** [comment]
Attached is a sample project. Note that i have just updated my vscode to v1.70, but issue persist.

[sbur-redis.zip](https://github.com/microsoft/vscode-gradle/files/9289436/sbur-redis.zip)

**Comment by CsCherrYY** [comment]
Thanks for the sample. Unfortunately, I still can't reproduce it on my PC (with 10+ tries). maybe this issue is related to system performance, and I would have another try in my laptop (with a worse performance)

Here are some findings:

1. we will start the debug session after `waitOnTcp()` promise:
https://github.com/microsoft/vscode-gradle/blob/e3992ea5b78f88b03afcaa73b4bbfc691024fc4f/extension/src/terminal/GradleRunnerTerminal.ts#L61-L76

2. In `waitOnTcp()` function, it will try to connect the target socket in `tcpExists()`, until it gets connected, and has a connect timeout 300ms and total timeout 10s.
https://github.com/microsoft/vscode-gradle/blob/e3992ea5b78f88b03afcaa73b4bbfc691024fc4f/extension/src/util/index.ts#L14-L46

**Comment by hannah23280** [comment]
Strange.. Is your vscode-java extension latest version?  My laptop is actually quite new..with amd i9 16gb.  Hence system performance should be considered good.
Hence I doubt it's related to system performance.

**Comment by 34will** [comment]
I agree that it's unlikely to be system performance as I am also experiencing this issue with an AMD 5900X on Desktop with 32GB of RAM on Windows 10. I also concur that it's not likely to be the timeout as I manually changed the timeout in the extension code and it had no effect. The project I am working on is: https://github.com/SleepyTrousers/EnderIO-Rewrite and I am trying to run the `runClient` gradle task, if you want to try that. I'm sorry it's not exactly a small sample project 😅 Also I am using the Oracle JDK 17, if that's likely to have any bearing.

**Comment by hannah23280** [comment]
I try to debug without going thru gradle, and i got error message "Missing Gradle project configuration file: .settings/org.eclipse.buildship.core.prefs". This issue has been raised out at the vscode-java github.  I mention this, cos not sure if this error message has anything to do with the "Failed to attach to remote debugee" in one way or another.

**Comment by CsCherrYY** [comment]
> I try to debug without going thru gradle, and i got error message "Missing Gradle project configuration file: .settings/org.eclipse.buildship.core.prefs". This issue has been raised out at the vscode-java github. I mention this, cos not sure if this error message has anything to do with the "Failed to attach to remote debugee" in one way or another.

The root cause of this issue is that your project has been imported via another way or there is any metadata files (.settings, .project and .classapth) ramaining. To solve this, I recommended:

- If you want to keep them in your project folder: See: https://github.com/redhat-developer/vscode-java/issues/2528#issuecomment-1166891481
- Otherwise, set `java.import.generatesMetadataFilesAtProjectRoot` to `false`(default value), delete all metadata files in your project folder and sub project folder, then clean workspace, this issue can be resolved.

BTW, I think this issue is not related to the debug issue, it's about the project importing.

**Comment by CsCherrYY** [comment]
I can reproduce this in @34will's  sample project, it seems that the extension try to start the debug session before the Gradle task is going to run. Let me investigate a bit more.

**Comment by hannah23280** [comment]
I presume this is still under investigation.

**Comment by CsCherrYY** [comment]
@hannah23280 sorry for late response. There was a PR tring to fix this issue via serveral retries, could you try if it works?

https://github.com/CsCherrYY/vscode-test/blob/main/vscode-gradle-3.12.5.vsix

**Comment by hannah23280** [comment]
> @hannah23280 sorry for late response. There was a PR tring to fix this issue via serveral retries, could you try if it works? 
> 
> https://github.com/CsCherrYY/vscode-test/blob/main/vscode-gradle-3.12.5.vsix

Hi, I have update the extension to v3.12.5 inside the vscode (but not from the link u show above,, which i presume its the same) but unfortunately the issue still persist

**Comment by CsCherrYY** [comment]
> > @hannah23280 sorry for late response. There was a PR tring to fix this issue via serveral retries, could you try if it works?
> > https://github.com/CsCherrYY/vscode-test/blob/main/vscode-gradle-3.12.5.vsix
> 
> Hi, I have update the extension to v3.12.5 inside the vscode (but not from the link u show above,, which i presume its the same) but unfortunately the issue still persist

Actually they are not the same :). The one I paste here comes from the private build in https://github.com/microsoft/vscode-gradle/pull/1272, which is not included in the offical release since I'm not confident this issue could be fixed via that PR. You can just uninstall the current one and install the one I provided manually to see if it works.

After that, you can re-install the one from the marketplace.

**Comment by hannah23280** [comment]
> I can reproduce this in @34will's sample project, it seems that the extension try to start the debug session before the Gradle task is going to run. Let me investigate a bit more.

I download the private build in #1272 and tested it out.  Run multiple times and not yet encounter the issue.  Seem to me, the fix work.
Since u have reproduced the issue in @34will 's sample project previously, does the issue goes away with this fix too?

**Comment by CsCherrYY** [comment]
Yeah I tested and it seems to be fixed in that project. It seems this issue can be regarded via serval retries... I will test more times and then release it via pre-release verisons to let more users see if it works.

**Comment by CsCherrYY** [comment]
@hannah23280 @34will @NogrTL I have investigated a new way which might fix this issue in https://github.com/microsoft/vscode-gradle/pull/1289. Would you mind trying it via pre-release `3.12.2022103106`?

**Comment by hannah23280** [comment]
Cool! But where to download the vsix for 3.12.2022103106

**Comment by CsCherrYY** [comment]
just click "switch to pre-release version" button, any version newer than `3.12.2022103106` will contain this change.

![image](https://user-images.githubusercontent.com/45906942/199139776-a789e200-b3bd-48f7-83cc-dcd947b538bf.png)

**Comment by hannah23280** [comment]
I presume 3.12.2022110100  has superceded the 3.12.2022103106. 
![image](https://user-images.githubusercontent.com/4410920/199158817-6645e1e9-69ef-447b-a846-0d6c1d7d636b.png)

Unfortunately, still encounter the same issue
![image](https://user-images.githubusercontent.com/4410920/199158974-de49cd42-4bee-4bb9-9ac6-32d474881012.png)

**Comment by CsCherrYY** [comment]
thank you @hannah23280, it looks like we should still apply the workaround in #1272...
