### ISSUE TITLE
duplicated Gradle tasks

### ISSUE THREAD

**Issue by CsCherrYY** [badsyntax/vscode-gradle#1262]
given:

1. https://docs.gradle.org/current/samples/zips/sample_building_java_applications_multi_project-groovy-dsl.zip
2. https://docs.gradle.org/current/samples/zips/sample_building_java_applications-groovy-dsl.zip

in the same workspace, in Gradle view, you will find serveral duplicate tasks 
![image](https://user-images.githubusercontent.com/45906942/182502286-b63ed6a6-bc9e-42fe-b78e-50cadc77ca4d.png)

**Comment by CsCherrYY** [comment]
To verify this: 

1. git clone https://github.com/CsCherrYY/gradle-test-multiple-workspace-root
2. open workspace defined in `test.code-workspace`
3. open Gradle view container, and wait until the project is imported
4. check project `sample_building_java_applications-groovy-dsl/demo` project and `sample_building_java_applications_multi_project-groovy-dsl/demo` project in the gradle projects view, can see there are no duplicate tasks found and both of them are showing correct results.

**Comment by Eskibear** [comment]
verified.
