### ISSUE TITLE
Missing release for v3.12.3

### ISSUE THREAD

**Issue by filiptronicek** [badsyntax/vscode-gradle#1267]
**Describe the bug**

Heya there 👋!
I was looking at the releases, and it seems like there is a mismatch: both on the [Microsoft Marketplace](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-gradle) and in [`package.json`](https://github.com/microsoft/vscode-gradle/blob/e3992ea5b78f88b03afcaa73b4bbfc691024fc4f/extension/package.json#L5) it is stated that the current version of the extension is `3.12.3`, but the latest release is only available for https://github.com/microsoft/vscode-gradle/releases/tag/3.12.2.

cc @CsCherrYY

**Comment by CsCherrYY** [comment]
Added in https://github.com/microsoft/vscode-gradle/releases/tag/3.12.3. Thanks for reminding!
