### ISSUE TITLE
input variables not supported in task args

### ISSUE THREAD

**Issue by dshick-nydig** [badsyntax/vscode-gradle#1281]
Extension Name: vscode-gradle
Extension Version: v3.12.4
OS Version: macOS Monterey
VSCode version: 1.70.2

**Describe the bug**
PR #1035 doesn't seem to have included support for [input variables ](https://code.visualstudio.com/docs/editor/variables-reference#_input-variables)

**To Reproduce**
Define a gradle workflow and reference an input variable from the args, e.g.
```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "gradle",
			"script": "app:run",
			"args": "-PfileToRun=${input:fileToRun}",
			...
		}
	],
	"inputs": [
		{
			"type": "pickString",
			"id": "fileToRun",
			"description": "What file do you want to run?",
			"options": [
				"File1",
				"File2"
			]
		},
	]
}
```

A possible build.gradle.kts might include...
```
application {
    // Define the main class for the application.
    mainClass.set("com.example." + project.findProperty("fileToRun").toString() + "Kt")
}
```

**Expected behavior**
the input variable should be dereferenced in the resulting command's arguments

**Output from "Gradle for Java"**
```
> :app:run
Error: Could not find or load main class com.example.${input:fileToRun}Kt
Caused by: java.lang.ClassNotFoundException: com.example.${input:fileToRun}Kt
```

**Does the bug still exist if you disable all other extensions?**
Yes

**Comment by CsCherrYY** [comment]
I can reproduce this bug. It seems that we didn't put the resolved args into execution args, I will fix it.
