### ISSUE TITLE
How to provide models like the BuildEnvironment to Gradle locally i.e. not via the internet

### ISSUE THREAD

**Issue by halloleo** [badsyntax/vscode-gradle#1304]
I am trying to use Gradle and the Gradle VS Code extension on a Linux machine without internet access.

I was able to install both, Gradle and the Gradle VS Code extension. Then I had to tell the  extension to use the _installed_ Gradle binary (and not try to download it again!) andnow the extension finds my local Gradle install. So far so good.

However, as soon as the VS Code extension wants to do something (like finding my tasks) it errors out with:

> [gradle-server] Could not fetch model of type ‘BuildEnvironment’ using connection to Gradle installation /path/to/gradle/install/bin/gradle

So, somehow I have to provide the BuildEnvironment model to the local gradle(-server). How do I do this? Where does Gradle stores these models locally on the machine? And from where can I download them (on another internet-connected machine of course)?

Thanks for any pointers!

**Comment by CsCherrYY** [comment]
where did you set the local installation path? the related VS Code setting should be `java.import.gradle.home`. 

And it should points a folder like `C:/Gradle/gradle-7.1`, and there are some folders such as `C:/Gradle/gradle-7.1/bin`, `C:/Gradle/gradle-7.1/lib` and `C:/Gradle/gradle-7.1/src`...

**Comment by halloleo** [comment]
Well, I did set it in `java.import.gradle.home`, ***but*** I entered the full path to the executable `.opt/gradle/gradle-7.5.1/bin/gradle`.

Now I changed it to `/opt/gradle/gradle-7.5.1` -- and Gradle now seems to find all the tasks in my project. 😄

Thanks a lot for your hint @CsCherrYY. Now I can continue setting up gradle for my project!
