### ISSUE TITLE
step input package name if contains . or / then doesn't input any character

### ISSUE THREAD

**Issue by crackfan** [badsyntax/vscode-gradle#1306]
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

Gradle for Java v3.12.5

![image](https://user-images.githubusercontent.com/2922399/204310531-37b0b748-09f7-4a17-ad76-f952341fec16.png)

not input any character is here!

**Comment by CsCherrYY** [comment]
the valid package name shouldn't end with a dot `.`. You can add characters and the error message will gone.

**Comment by crackfan** [comment]
version 3.12.6 was repaire! Thank you so much!
