### ISSUE TITLE
gradlew works, but plugin throws error

### ISSUE THREAD

**Issue by ImanHosseini** [badsyntax/vscode-gradle#1309]
Extension Name: vscode-gradle
Extension Version: latest
OS Version: WSL2
VSCode version: latest

When I run from terminal:
```
./gradlew build
```
it works. BUT when I do it from the Gradle plugin (using the run task button form the GUI) it fails with:
```
error: package com.sun.javadoc does not exist
import com.sun.javadoc.Tag;
```
I _think_ this is due to the fact that project needs jdk 1.8 which it picks up when I do gradlew from terminal BUT from gradle, it tries to use jdk 11 - which is too new - and it fails.
How do I fix this?

**Comment by CsCherrYY** [comment]
the extension picks the value of `java.import.gradle.java.home` as the java home. you can set it the same as the system JAVA_HOME to keep them consistent.

**Comment by ImanHosseini** [comment]
This is what's stumping me, 
```
JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64 ./gradlew build
```
The above succeeds. And so I add this to .vscode/settings.json:
```
{
    "java.import.gradle.java.home": "/usr/lib/jvm/java-1.8.0-openjdk-amd64",
}
```
Now running build by clicking on the gradle button from the extension should work too right? But it doesn't! Throws that same error that happens when you use a newer java version. 
It works now: I restarted VScode and it was fixed. Thank you.
